services:

  dokuwiki-dev:
    image: linuxserver/dokuwiki:2025-05-14a-ls271
    profiles: ["development"]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    ports:
      - "${DEV_PORT:-8080}:80"
    volumes:
      - ./data:/config

  dokuwiki-prod:
    image: linuxserver/dokuwiki:2025-05-14a-ls271
    restart: unless-stopped
    profiles: ["production"]
    networks:
      - webproxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ./data:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"

  backup-dev:
    image: alpine:3.18
    profiles: ["development"]
    depends_on:
      - dokuwiki-dev
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      - BACKUP_FREQ=${BACKUP_FREQ:-240}
      - RETENTION_DAYS=${RETENTION_DAYS:-30}
      - ENVIRONMENT=development
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./data:/config:ro
      - ./backups:/backups
      - ./scripts:/app:ro
    command: /app/run-backup.sh
    restart: unless-stopped

  backup-prod:
    image: alpine:3.18
    profiles: ["production"]
    depends_on:
      - dokuwiki-prod
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      - BACKUP_FREQ=${BACKUP_FREQ:-240}
      - RETENTION_DAYS=${RETENTION_DAYS:-30}
      - ENVIRONMENT=production
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./data:/config:ro
      - ./backups:/backups
      - ./scripts:/app:ro
    command: /app/run-backup.sh
    restart: unless-stopped

networks:
  webproxy:
    external: true
